services:
  app:
    build:
      context: ../ # El contexto es el directorio padre (raíz del proyecto)
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ../:/var/www # Monta el directorio raíz del proyecto en /var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: db_password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:


networks:
  app-network:
    driver: bridge
